# Generated by Django 4.0.4 on 2022-07-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Release_Date', models.DateField()),
                ('Genre', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
